notifications:
  email: false

language: python
python:
    - "2.7"
#    - "3.4"

sudo: false

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

before_install:
    # Setup anaconda
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy hdf4 netcdf4 matplotlib basemap
    - conda env create --file environment.yml
    - source activate py2_parcels
    - pip install -e .

before_script: # configure a headless display to test plot generation
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

script:
    - export PYTHONPATH=`pwd`:$PYTHONPATH
    - flake8 parcels
    - flake8 tests
    - flake8 examples
    - python parcels/scripts/pull_data.py
    - py.test -v -s tests/
    - py.test -v -s --nbval-lax examples/
