name: py2_parcels
channels:
  - conda-forge
dependencies:
  - cachetools
  - cgen
  - coverage
  - enum34
  - ffmpeg
  - flake8
  - gcc_linux-64
  - git
  - jupyter
  - matplotlib
  - netcdf4
  - numpy
  - progressbar2
  - py
  - pymbolic
  - python-dateutil
  - scipy
  - six
  - xarray
  - pip:
      - pytest
      - nbval
